// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZ5Dqk3XBWCptCwXUvrWvfBNR1zNYyHc',
    appId: '1:860267795273:web:b43ddae255b99816064098',
    messagingSenderId: '860267795273',
    projectId: 'filmov-net',
    authDomain: 'filmov-net.firebaseapp.com',
    storageBucket: 'filmov-net.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMcCA0ams_-HyeFidTyKBllwi63SIe8ns',
    appId: '1:860267795273:android:29d96f128737bb60064098',
    messagingSenderId: '860267795273',
    projectId: 'filmov-net',
    storageBucket: 'filmov-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bbHwp0yYw96aWepaPlPD7ffkyz17Rbk',
    appId: '1:860267795273:ios:df00dcc6cae6611d064098',
    messagingSenderId: '860267795273',
    projectId: 'filmov-net',
    storageBucket: 'filmov-net.firebasestorage.app',
    iosBundleId: 'com.example.cinematch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3bbHwp0yYw96aWepaPlPD7ffkyz17Rbk',
    appId: '1:860267795273:ios:df00dcc6cae6611d064098',
    messagingSenderId: '860267795273',
    projectId: 'filmov-net',
    storageBucket: 'filmov-net.firebasestorage.app',
    iosBundleId: 'com.example.cinematch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZ5Dqk3XBWCptCwXUvrWvfBNR1zNYyHc',
    appId: '1:860267795273:web:83d937d0d1394355064098',
    messagingSenderId: '860267795273',
    projectId: 'filmov-net',
    authDomain: 'filmov-net.firebaseapp.com',
    storageBucket: 'filmov-net.firebasestorage.app',
  );
}
